llm_pricing:
  claude-3.5-sonnet:
    input: 0.003
    output: 0.015
  gemini-1.5-flash:
    input: 0.001
    output: 0.002
  deepseek-coder:
    input: 0.0005
    output: 0.001
gcp_pricing:
  compute_engine:
    n1-standard-1: 0.0475
  cloud_storage:
    standard: 0.020
other_services:
  serpapi:
    basic_plan: 50
