tool_dependencies:
- primary: supabase
  requires: mcp
- primary: github_mcp
  requires: mcp
- primary: puppeteer
  requires: mcp
- primary: sequential_thinking
  requires: mcp
- primary: memory
  requires: mcp
- primary: browser_tools
  requires: mcp
- primary: mac_apps
  requires: mcp
- primary: docker_mcp
  requires: mcp
- primary: brave_search
  requires: mcp
- primary: playwright
  requires: mcp
- primary: stripe
  requires: mcp
- primary: chromadb
  requires: mcp
- primary: google_calendar
  requires: mcp
- primary: gmail
  requires: mcp
- primary: secrets_manager
  requires: code_execution
- primary: data_analysis
  requires: code_execution

tools:
- name: web_search
  description: Search the web for information
  implementation: core.tools.web_search.search
  parameters:
    query: string
    max_results: integer

- name: secrets_manager
  description: Manage secure credentials and secrets
  implementation: core.tools.secrets_manager.manage_secrets
  parameters:
    action: string
    key: string
    value: string

- name: memory_manager
  description: Manage persistent memory for agents
  implementation: core.tools.memory.manage_memory
  parameters:
    action: string
    key: string
    data: object

- name: code_generation
  description: Generate code, tests, and documentation
  implementation: core.tools.code_generation.generate
  parameters:
    spec: object
    language: string
    framework: string
    output_type: string
    context: object

- name: code_execution
  description: Execute code snippets
  implementation: core.tools.code_execution.execute
  parameters:
    code: string
    language: string
    timeout: integer

- name: github_tool
  description: Interact with GitHub repositories
  implementation: core.tools.github_tool.github_action
  parameters:
    action: string
    payload: object
    repo: string

- name: github_mcp
  description: MCP server for GitHub operations
  implementation: core.tools.github_mcp.github_mcp_server
  parameters:
    action: string
    args: object

- name: puppeteer
  description: Browser automation with Puppeteer
  implementation: core.tools.puppeteer.puppeteer_action
  parameters:
    action: string
    url: string
    options: object

- name: browser_tools
  description: Browser interaction tools
  implementation: core.tools.browser_tools.browser_action
  parameters:
    action: string
    selector: string
    value: string

- name: bayesian_update
  description: Update Bayesian beliefs using PyMC
  implementation: core.tools.bayesian_tools.update_beliefs
  parameters:
    evidence: object
    model: string

- name: data_analysis
  description: Analyze data using various methods
  implementation: core.tools.data_analysis.analyze_data
  parameters:
    data: object
    method: string
    options: object
