tool_dependencies:
- primary: supabase
  requires: mcp
- primary: github_mcp
  requires: mcp
- primary: puppeteer
  requires: mcp
- primary: sequential_thinking
  requires: mcp
- primary: memory
  requires: mcp
- primary: browser_tools
  requires: mcp
- primary: mac_apps
  requires: mcp
- primary: docker_mcp
  requires: mcp
- primary: brave_search
  requires: mcp
- primary: playwright
  requires: mcp
- primary: stripe
  requires: mcp
- primary: chromadb
  requires: mcp
- primary: google_calendar
  requires: mcp
- primary: gmail
  requires: mcp
tools:
- description: Core Model Context Protocol operations
  implementation: core.tools.mcp.standard_operations
  name: mcp
  parameters:
    context_id: string
    data: object
    operation: string
    query: string
    server: string
- description: Supabase-specific MCP implementation for vector storage and retrieval
  implementation: core.tools.mcp_servers.supabase_operations
  name: supabase
  parameters:
    data: object
    filters: object
    operation: string
    table: string
- description: GitHub operations through MCP
  implementation: core.tools.mcp_servers.github_operations
  name: github_mcp
  parameters:
    data: object
    operation: string
    owner: string
    repo: string
- description: Web automation and scraping with Puppeteer
  implementation: core.tools.mcp_servers.puppeteer_operations
  name: puppeteer
  parameters:
    operation: string
    script: string
    url: string
- description: Sequential reasoning tool for complex problem solving
  implementation: core.tools.mcp_servers.sequential_thinking_operations
  name: sequential_thinking
  parameters:
    operation: string
    problem: string
    steps: integer
- description: Long-term memory storage and retrieval
  implementation: core.tools.mcp_servers.memory_operations
  name: memory
  parameters:
    data: object
    memory_id: string
    operation: string
- description: Browser-based tools for web interactions
  implementation: core.tools.mcp_servers.browser_tools_operations
  name: browser_tools
  parameters:
    action: string
    operation: string
    url: string
- description: Integration with macOS applications
  implementation: core.tools.mcp_servers.mac_apps_operations
  name: mac_apps
  parameters:
    app: string
    command: string
    operation: string
- description: Docker container management
  implementation: core.tools.mcp_servers.docker_operations
  name: docker_mcp
  parameters:
    command: string
    container: string
    operation: string
- description: Private search using Brave Search
  implementation: core.tools.mcp_servers.brave_search_operations
  name: brave_search
  parameters:
    filters: object
    operation: string
    query: string
- description: Advanced web automation with Playwright
  implementation: core.tools.mcp_servers.playwright_operations
  name: playwright
  parameters:
    operation: string
    script: string
    url: string
- description: Payment processing with Stripe
  implementation: core.tools.mcp_servers.stripe_operations
  name: stripe
  parameters:
    action: string
    data: object
    operation: string
- description: ChromaDB vector database integration
  implementation: core.tools.mcp_servers.chromadb_operations
  name: chromadb
  parameters:
    collection: string
    metadata: object
    operation: string
    vectors: array
- description: Google Calendar integration
  implementation: core.tools.mcp_servers.google_calendar_operations
  name: google_calendar
  parameters:
    action: string
    event: object
    operation: string
- description: Gmail integration for email operations
  implementation: core.tools.mcp_servers.gmail_operations
  name: gmail
  parameters:
    action: string
    email: object
    operation: string
- description: Search the web for information
  implementation: core.tools.web_search.search
  name: web_search
  parameters:
    max_results: integer
    query: string
- description: Execute code snippets
  implementation: core.tools.code_execution.execute
  name: code_execution
  parameters:
    code: string
    language: string
    timeout: integer
- description: Interact with GitHub repositories
  implementation: core.tools.github_tool.github_action
  name: github_tool
  parameters:
    action: string
    payload: object
    repo: string
- description: Update Bayesian beliefs using PyMC
  implementation: core.tools.bayesian_tools.update_beliefs
  name: bayesian_update
  parameters:
    evidence: object
    model: string
- description: Analyze documents for structure, content, and code
  implementation: core.tools.document_analyzer.analyze_document
  name: document_analyzer
  parameters:
    analysis_type: string
    file_path: string
    options: object
- description: Generate code, tests, and documentation
  implementation: core.tools.code_generation.generate
  name: code_generation
  parameters:
    spec: object
    language: string
    framework: string
    output_type: string
    context: object
