# Example Playbook for WrenchAI CLI testing

id: example
title: Example Playbook
description: A simple example playbook for testing the WrenchAI CLI

agents:
  - SuperAgent
  - CodeGeneratorAgent
  - InspectorAgent

agent_llms:
  SuperAgent: claude-3.5-sonnet-20240229
  CodeGeneratorAgent: claude-3.5-sonnet-20240229
  InspectorAgent: claude-3.5-sonnet-20240229

mcp_servers:
  - context7
  - python_exec

parameters:
  - name: project_name
    type: string
    description: Name of the project
    required: true
  - name: language
    type: string
    description: Programming language to use
    required: true
    default: python
  - name: include_tests
    type: boolean
    description: Whether to include tests
    required: false
    default: true

steps:
  - step_id: gather_requirements
    type: standard
    description: "Gather requirements for the project"
    agent: SuperAgent
    operation: "gather_requirements"
    tools:
      - web_search
      - memory
    next: generate_code
    
  - step_id: generate_code
    type: standard
    description: "Generate code for the project"
    agent: CodeGeneratorAgent
    operation: "generate_code"
    tools:
      - code_generator
      - file_manager
    next: inspect_code
    
  - step_id: inspect_code
    type: standard
    description: "Inspect code for issues"
    agent: InspectorAgent
    operation: "inspect_code"
    tools:
      - code_analyzer
    next: null