# Repository Setup Playbook
name: "Repository Setup"
description: "Set up a new repository with standard configuration"

steps:
  - step_id: 1
    name: "Create Standard Labels"
    action: "manage_labels"
    input:
      labels:
        # Phase labels
        - name: "phase: mvp-1"
          color: "C2E0C6"
          description: "MVP Phase 1: Core Functionality"
        - name: "phase: mvp-2"
          color: "C2E0C6"
          description: "MVP Phase 2: Testing & Quality"
        - name: "phase: post-mvp"
          color: "C2E0C6"
          description: "Post-MVP Enhancements"
        
        # Priority labels
        - name: "priority: p0"
          color: "D93F0B"
          description: "Critical for MVP functionality"
        - name: "priority: p1"
          color: "D93F0B"
          description: "Important for MVP but not blocking"
        
        # Component labels
        - name: "component: core"
          color: "0366D6"
          description: "Core framework functionality"
        - name: "component: ui"
          color: "0366D6"
          description: "User interface related"
        - name: "component: docs"
          color: "0366D6"
          description: "Documentation related"

  - step_id: 2
    name: "Create Project Board"
    action: "setup_project_board"
    input:
      name: "MVP Development"
      columns:
        - "To Do"
        - "In Progress"
        - "Review"
        - "Done"
      automation:
        - rule: "auto_add_to_todo"
          when: "issue_created"
          action: "move_to_column"
          column: "To Do"
        - rule: "auto_move_to_done"
          when: "issue_closed"
          action: "move_to_column"
          column: "Done"

  - step_id: 3
    name: "Create Initial Issues"
    action: "create_issues_from_template"
    input:
      template: "task"
      project: "MVP Development"
      tasks:
        - title: "Set up development environment"
          description: "Create and document the development environment setup"
          objectives: |
            - Configure development tools
            - Set up virtual environment
            - Document prerequisites
            - Create setup script
          acceptance_criteria: |
            - [ ] Development tools configured
            - [ ] Virtual environment working
            - [ ] Documentation complete
            - [ ] Setup script tested
          implementation_notes: |
            - Use venv for Python environment
            - Include all necessary tools
            - Consider cross-platform compatibility
          resources: |
            - Python documentation
            - Tool documentation
          estimated_time: "2 days"
          story_points: 3
          labels:
            - "phase: mvp-1"
            - "priority: p0"
            - "component: core"

error_handling:
  max_retries: 3
  retry_delay: 1
  on_failure: "notify"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
